version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - rubcamp
    environment:
      - POSTGRES_DB=rubcamp
      - POSTGRES_USER=rubcamp
      - POSTGRES_PASSWORD=rubcamp123
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build:
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3344:3344
    networks:
      - rubcamp
    links:
      - db
    env_file:
      - .env.example
    platform: 'linux/amd64'
    depends_on:
      db:
        condition: service_healthy

  web_test:
    container_name: web_test
    build:
      dockerfile: Dockerfile.dev
    command: yarn test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rubcamp
    links:
      - db
    env_file:
      - .env.example
    platform: 'linux/amd64'
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started

networks:
  rubcamp:
    driver: bridge
