export enum AppErrorCodes {
	UNAUTHORIZED = 'UNAUTHORIZED',
	UNAUTHENTICATED = 'UNAUTHENTICATED',
	INVALID_OPERATION = 'INVALID_OPERATION',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	INVALID_PARAMETER = 'INVALID_PARAMETER',
	RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
	NOT_FOUND = 'NOT_FOUND',

	VERIFICATION_PROVIDER_ERROR = 'VERIFICATION_PROVIDER_ERROR',
	INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',

	WRONG_TRANSACTIONAL_PASSWORD = 'WRONG_TRANSACTIONAL_PASSWORD',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	BLOCKED_ACCOUNT = 'BLOCKED_ACCOUNT',
	LOCKED_ACCOUNT = 'LOCKED_ACCOUNT',
	CLOSED_ACCOUNT = 'CLOSED_ACCOUNT',
	MAX_VERIFICATION_ATTEMPTS_ERROR = 'MAX_VERIFICATION_ATTEMPTS_ERROR'
}
