export enum AppErrorCodes {
	INVALID_OPERATION = 'INVALID_OPERATION',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	INVALID_PARAMETER = 'INVALID_PARAMETER',
	RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
	NOT_FOUND = 'NOT_FOUND',

	WRONG_TRANSACTIONAL_PASSWORD = 'WRONG_TRANSACTIONAL_PASSWORD',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	BLOCKED_ACCOUNT = 'BLOCKED_ACCOUNT'
}
