export enum ViolationCodes {
	REQUIRED = 'REQUIRED',
	BAD_LENGTH = 'BAD_LENGTH',
	MAX_LENGTH = 'MAX_LENGTH',
	MIN_LENGTH = 'MIN_LENGTH',
	CHOICES = 'CHOICES',

	WRONG_UUID_FORMAT = 'WRONG_UUID_FORMAT',
	WRONG_TYPE = 'WRONG_TYPE',
	WRONG_FORMAT = 'WRONG_FORMAT',
	BAD_PASSWORD_LENGTH = 'BAD_PASSWORD_LENGTH',
	BAD_PASSWORD_FORMAT = 'BAD_PASSWORD_FORMAT',
	INVALID_BIRTHDAY = 'INVALID_BIRTHDAY',
	INVALID_PHONE = 'INVALID_PHONE',
	INVALID_EMAIL = 'INVALID_EMAIL',
	INVALID_DOCUMENT = 'INVALID_DOCUMENT',
	INVALID_AMOUNT_RANGE = 'INVALID_AMOUNT_RANGE',
	INVALID_SCHEDULED_DATE = 'INVALID_SCHEDULED_DATE',
	NEW_PASSWORD_EQUAL_OLD = 'NEW_PASSWORD_EQUAL_OLD',
	WRONG_OLD_PASSWORD = 'WRONG_OLD_PASSWORD',

	EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED'
}
